Traceback (most recent call last):
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/envs/book/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/share/miniconda/envs/book/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
error_promedio = np.abs(promedios - 0)

plt.loglog(N, np.std(x) / np.sqrt(N), label=r"s / $\sqrt{N}$")
plt.scatter(N, error_promedio, label=r"$|\bar{x} - \mu|$")
plt.xlabel("NÃºmero de mediciones $N$")
plt.ylabel("Error del promedio")
plt.legend()
plt.grid()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-19-24be7569df50>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0merror_promedio[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0mabs[0m[0;34m([0m[0mpromedios[0m [0;34m-[0m [0;36m0[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0mplt[0m[0;34m.[0m[0mloglog[0m[0;34m([0m[0mN[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mstd[0m[0;34m([0m[0mx[0m[0;34m)[0m [0;34m/[0m [0mnp[0m[0;34m.[0m[0msqrt[0m[0;34m([0m[0mN[0m[0;34m)[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34mr"s / $\sqrt{N}$"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mscatter[0m[0;34m([0m[0mN[0m[0;34m,[0m [0merror_promedio[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34mr"$|\bar{x} - \mu|$"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mxlabel[0m[0;34m([0m[0;34m"NÃºmero de mediciones $N$"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'promedios' is not defined
NameError: name 'promedios' is not defined

